[2024-06-12T08:17:52.772+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_to_s3_to_redshift.load_to_redshift manual__2024-06-12T08:17:28.111279+00:00 [queued]>
[2024-06-12T08:17:52.809+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_to_s3_to_redshift.load_to_redshift manual__2024-06-12T08:17:28.111279+00:00 [queued]>
[2024-06-12T08:17:52.809+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-12T08:17:52.809+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-06-12T08:17:52.810+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-12T08:17:52.891+0000] {taskinstance.py:1300} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2024-06-12 08:17:28.111279+00:00
[2024-06-12T08:17:52.910+0000] {standard_task_runner.py:55} INFO - Started process 11615 to run task
[2024-06-12T08:17:52.920+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_redshift', 'load_to_redshift', 'manual__2024-06-12T08:17:28.111279+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/test_redshift_real.py', '--cfg-path', '/tmp/tmp7j5uxpsa']
[2024-06-12T08:17:52.921+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask load_to_redshift
[2024-06-12T08:17:53.156+0000] {task_command.py:388} INFO - Running <TaskInstance: api_to_s3_to_redshift.load_to_redshift manual__2024-06-12T08:17:28.111279+00:00 [running]> on host be394f3a6896
[2024-06-12T08:17:53.366+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_to_s3_to_redshift
AIRFLOW_CTX_TASK_ID=load_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2024-06-12T08:17:28.111279+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-12T08:17:28.111279+00:00
[2024-06-12T08:17:53.399+0000] {base.py:73} INFO - Using connection ID 'aws_s3' for task execution.
[2024-06-12T08:17:53.418+0000] {base.py:73} INFO - Using connection ID 'aws_s3' for task execution.
[2024-06-12T08:17:53.420+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-06-12T08:17:53.448+0000] {s3_to_redshift.py:164} INFO - Executing COPY command...
[2024-06-12T08:17:53.471+0000] {base.py:73} INFO - Using connection ID 'redshift_test_dev' for task execution.
[2024-06-12T08:17:54.712+0000] {sql.py:375} INFO - Running statement: 
                    COPY yusuyeon678.raw_data_test_youngjun 
                    FROM 's3://dust-dag/dataSource/api_data.csv'
                    credentials
                    'aws_access_key_id=AKIAZQ3DNY2P6X5UNXUG;aws_secret_access_key=***'
                    csv
			IGNOREHEADER 1;
        , parameters: None
[2024-06-12T08:17:55.041+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 165, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'raw_data_test_youngjun' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '741', 'R': 'CheckMaxRowError'}
[2024-06-12T08:17:55.060+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_redshift, task_id=load_to_redshift, execution_date=20240612T081728, start_date=20240612T081752, end_date=20240612T081755
[2024-06-12T08:17:55.099+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task load_to_redshift ({'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'raw_data_test_youngjun' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '741', 'R': 'CheckMaxRowError'}; 11615)
[2024-06-12T08:17:55.158+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-12T08:17:55.200+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
